# Proyecto Aprendizaje de Máquina 2026-20
## Clasificación de sentimiento de reseñas en español

**Estudiante:** Santiago Serrano

### Objetivo
Construir un modelo clásico de aprendizaje automático capaz de clasificar
una reseña como negativa, neutral o positiva.

En esta primera etapa se utilizarán técnicas de representación de texto
como TF-IDF y n-gramas junto con modelos clásicos de scikit-learn.

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

import matplotlib.pyplot as plt

In [4]:
train = pd.read_csv("data/train.csv")
eval_df = pd.read_csv("data/eval.csv")
sample_submission = pd.read_csv("data/sample_submission.csv")

In [5]:
print("Train:", train.shape)
print("Eval:", eval_df.shape)

display(train.head())
display(eval_df.head())

Train: (12000, 3)
Eval: (3000, 2)

   id                                               text     label
0   0  Lo pedí un martes por la noche y me llegó al d...   neutral
1   1  Se lo compré a un familiar después de pensarla...  positivo
2   2  Lo pedí a mediados de mes y me llegó en tres d...  negativo
3   3  Compré esto en línea y llegó en unos tres días...  negativo
4   4  Compré este kit el mes pasado porque necesitab...  positivo

   id                                               text
0   0  Hice el pedido desde la aplicacion un martes p...
1   1  Compre esto a principios de mes porque andaba ...
2   2  Lo pedí un martes y me llegó el jueves a la ca...
3   3  Me llegó el miércoles pasado, tres días despué...
4   4  Lo pedí un martes y llegó el jueves a la casa....

In [6]:
print("Nulos en train:")
print(train.isnull().sum())

print("\nDuplicados:")
print(train.duplicated().sum())

print("\nDistribución de clases:")
print(train["label"].value_counts())

print("\nDistribución porcentual:")
print(
    train["label"].value_counts(
        normalize=True
    )
)

Nulos en train:
id       0
text     0
label    0
dtype: int64

Duplicados:
0

Distribución de clases:
label
positivo    4212
negativo    4212
neutral     3576
Name: count, dtype: int64

Distribución porcentual:
label
positivo    0.351
negativo    0.351
neutral     0.298
Name: proportion, dtype: float64